### ISSUE TITLE
N: keep getting  java.lang.RuntimeException in log when clicking recent button

### ISSUE THREAD

**Issue by rancidfrog** [DirtyUnicorns/android_packages_apps_OmniSwitch#1]
```
01-01 03:03:40.526  1184  2756 E ActivityManager: java.lang.Throwable
01-01 03:03:40.526  1184  2756 E ActivityManager:   at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:17703)
01-01 03:03:40.526  1184  2756 E ActivityManager:   at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18269)
01-01 03:03:40.526  1184  2756 E ActivityManager:   at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:499)
01-01 03:03:40.526  1184  2756 E ActivityManager:   at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2755)
01-01 03:03:40.526  1184  2756 E ActivityManager:   at android.os.Binder.execTransact(Binder.java:565)
01-01 03:03:40.551  3193  4297 W Resources: Drawable com.android.settings:drawable/ic_settings_data_usage has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
01-01 03:03:40.551  3193  4297 W Resources: java.lang.RuntimeException
01-01 03:03:40.551  3193  4297 W Resources:     at android.content.res.Resources.getDrawable(Resources.java:742)
01-01 03:03:40.551  3193  4297 W Resources:     at org.omnirom.omniswitch.RecentTasksLoader.getFullResIcon(RecentTasksLoader.java:432)
01-01 03:03:40.551  3193  4297 W Resources:     at org.omnirom.omniswitch.RecentTasksLoader.loadTaskIcon(RecentTasksLoader.java:397)
01-01 03:03:40.551  3193  4297 W Resources:     at org.omnirom.omniswitch.RecentTasksLoader$1.doInBackground(RecentTasksLoader.java:348)
01-01 03:03:40.551  3193  4297 W Resources:     at org.omnirom.omniswitch.RecentTasksLoader$1.doInBackground(RecentTasksLoader.java:245)
01-01 03:03:40.551  3193  4297 W Resources:     at android.os.AsyncTask$2.call(AsyncTask.java:304)
01-01 03:03:40.551  3193  4297 W Resources:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-01 03:03:40.551  3193  4297 W Resources:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-01 03:03:40.551  3193  4297 W Resources:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-01 03:03:40.551  3193  4297 W Resources:     at java.lang.Thread.run(Thread.java:761)
01-01 03:03:41.093  1184  2608 E ActivityManager: Sending non-protected broadcast org.omnirom.omniswitch.ACTION_TOGGLE_OVERLAY from system 1921:com.android.systemui/u0a27 pkg com.android.systemui
```

**Comment by HaoZeke** [comment]
Was this fixed? I've been getting this too..

**Comment by Mazda--** [comment]
This has long been fixed.
